[build]
  functions = "netlify/functions"
  command = "npm run build" # if you have a build step, adjust as needed

[[redirects]]
  from = "/api/frame-url/*"
  to = "/.netlify/functions/frame-url?frameNumber=:splat"
  status = 200

[[redirects]]
  from = "/"
  to = "/views/index.ejs"
  status = 200
