[build]
  command = "npm start"
  functions = "netlify/functions"
  publish = "views"

[[redirects]]
  from = "/api/frame-url/*"
  to = "/.netlify/functions/frame-url?frameNumber=:splat"
  status = 200

[[redirects]]
  from = "/"
  to = "/pacific"
  status = 200
