[build]
  functions = "netlify/functions"

[[redirects]]
  from = "/api/frame-url/*"
  to = "/.netlify/functions/frame-url?frameNumber=:splat"
  status = 200

[[redirects]]
  from = "/"
  to = "/pacific"
  status = 200
